workflows:
  android-apk-build:
    environment:
      flutter: 3.44.1

    scripts:
      - flutter build apk --release --target-platform android-arm64
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
